### ISSUE TITLE
Zoho - mise à jour des comptes/achats/ventes

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/rtfm#21]
ça se passe là:
- gitbook : https://github.com/openfab-lab/rtfm/tree/master/faq/accounting
- le template d'issue : https://github.com/openfab-lab/devis-et-facturation/blob/master/.github/ISSUE_TEMPLATE/accounting-template.md

---

J'ai commencé à transmettre mon savoir comptable à @DewiBrunet 

On s'est fait une todoList à suivre pour faire le check compta 1x par semaine. 

- [ ] SALES #7 
  - [x] vérifier le carnet laser, encoder et envoyer les factures adhoc #4 
  - [x] valider les factures aux membres, aux clients si des factures récurrentes on été créée en "draft" 
![image](https://user-images.githubusercontent.com/12049360/54280296-6a75e400-4597-11e9-8d99-2055785496ca.png)
  - [ ] Au besoin, encoder les nouveaux clients, nouveaux membres.  #13 
  - [ ] Enregistrer les factures récurrentes pour inscription asbl et membership 
 
- [ ] PuuuuurCHASES #6 
  - [ ] Collecter les tickets et factures (achats par bancontact, factures, achats en ligne amazon, Aliexpress, etc... )
  - [ ] Scanner les docs papiers, les ajouter à la farde rouge "Achat 2019" et tout réunir sur le NAS dans `compta/factureIN`
  - [ ] Encoder les achats déjà payé comme **Expenses**, avec en pièce jointe les justificatifs. 
  - [ ] Encoder les achats à payer comme **Bills**, principalement des factures d'internet, douane, assurance, smartbe, etc... ainsi que note de frais staff. #10 
 
- [x] Payer les **Bills** 
 Aller sur le compte en ligne, et enregistrer les virements "Open et Overdue"
![image](https://user-images.githubusercontent.com/12049360/54281434-07398100-459a-11e9-84d9-08e6d095b069.png)

- [x] Télécharger les extraits 
selon **import statements** #3 

- [x] catégoriser les mouvements = match entre encodage et mouvement bancaire. 
Ce qui modifie le status des factures clients et factures fournisseurs en attente, résumée dans le dashboard tout en haut. 
![image](https://user-images.githubusercontent.com/12049360/54281558-449e0e80-459a-11e9-8111-41c293b07fa3.png)

**Comment by nicolasdb** [comment]
Bonus, 
Ajouter les achats de matos à revendre dans les "items" et associer au compte "Cost of Goods Sold"
J'ai pris le parti de majorer à 40% pour les achats Europe, 60% les achats Aliexpress.

**Comment by nicolasdb** [comment]
Créer une issue sur devis/facturation 
https://github.com/openfab-lab/devis-et-facturation/issues
![image](https://user-images.githubusercontent.com/12049360/65771935-8ad34d80-e139-11e9-8060-40a01c0d1c04.png)


Choisir le template compta. 
![image](https://user-images.githubusercontent.com/12049360/65771952-90c92e80-e139-11e9-9f0b-fe470cc7dafd.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/67000753-b3b38680-f0d8-11e9-8b6d-15e30a35e881.png)

**Comment by nicolasdb** [comment]
Mise à jour de la documentation, des petites modifs ont été apportée en 2021
Apprentissage entamé avec Navid et Francis.
![image](https://user-images.githubusercontent.com/12049360/106889942-ff80a980-66e8-11eb-9d39-7f3912eb41df.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/106891638-47083500-66eb-11eb-8f9f-fe8f2d26604b.png)
